### ISSUE TITLE
Display title_annotation if present

### ISSUE THREAD

**Issue by sighmon** [ACMILabs/interactive-label#38]
- [x] Implement css to display `title_annotation` field from the works serializer next to the Title, possibly with decoration such as square brackets.

**Comment by cogat** [comment]
@pippshea to provide designs (approved by Lucie, Matt)

**Comment by cogat** [comment]
![Cabinet of curosities 1920 x 1080px - 2 coloumn text - 1 image - Example B (1).png](https://images.zenhubusercontent.com/5c56ba66fd8e3861b7794f29/c98cdcc4-b418-48c7-9b40-536d0b594ce7)
![Playlist labels - Portrait - Example A.png](https://images.zenhubusercontent.com/5c56ba66fd8e3861b7794f29/a5a5ce77-2cc2-465c-89b0-dae327219e65)

This is 16pt lowercase Fakt Pro normal weight, preceded by a 21pt space.
