### ISSUE TITLE
Set interactive labels for curators' UAT

### ISSUE THREAD

**Issue by framigni** [ACMILabs/interactive-label#55]
- [x] make sure we have 13x interactive labels devices up and running in the gallery, covering all 13 labels' options, including the FSF location
- [x] test that all displays can be visible via browser, after VPN authentication
- [x] provide a list of all 13 devices to Matt Millikan, including exhibition location and URL addresses
- [x] ask Matt what'll be his time frame for running the UAT (when he can start) - From **Matt**: I'm going to try do a first pass of them all tomorrow and then double-check with Chelsey next week
- [x] report back to Boojum, and Lucie

**Comment by framigni** [comment]
@alihaberfield @sighmon 
please review this ticket and let me know if anything missing

**Comment by alihaberfield** [comment]
I'll just add a note here that in order to preview the interactive label backgrounds accurately, Matt should set his resolution to 1920 x 1080px.
