### ISSUE TITLE
Improved GPU performance

### ISSUE THREAD

**Issue by sighmon** [ACMILabs/interactive-label#66]
This Balena forum post implies that better GPU performance can be had using `libgl1-mesa-dri` - so might be good to try that including the sym link @hvanness https://forums.balena.io/t/running-chromium-with-video-in-kiosk-mode-on-an-intel-nuc-with-balena/32061/9

**Comment by hvanness** [comment]
Added this to the top of scripts/x86 to no avail:
apt install libgl1-mesa-dri && ln -s /usr/lib/x86_64-linux-gnu/dri /usr/lib/dri
