### ISSUE TITLE
Touchscreen Calibration

### ISSUE THREAD

**Issue by hvanness** [ACMILabs/interactive-label#81]
- [ ] Calibrate [MW-04-LR01](https://xos.acmi.net.au/admin/exhibitions/device/283/change/?_changelist_filters=q%3DMW-04-LR01)

The touchscreens we're using require calibration.

The command to get the touchscreen calibration output: `xinput_calibration --output-type x_input`

Save this calibration to an environment variable in [XOS Device](https://xos.acmi.net.au/admin/exhibitions/device/283/change/?_changelist_filters=q%3DMW-04-LR01), `TOUCH_CALIBRATION`, eg. `32 246 4102 0 3960`

^^^ that's the calibration Harry has already tried.

**Comment by hvanness** [comment]
Just reviewed the touchscreen calibration, looks like some screens are "uncalibratable" since we can't resolve their non-linear response. I'd need to see the cursor for hard evidence of the non-linearity, but simply using xinput_calibrator isn't working eg. for MW-04-LR01

**Comment by sam-maher-acmi** [comment]
Attempting to resolve the transformation calibration with https://github.com/ACMILabs/interactive-label/pull/102
